### ISSUE TITLE
Strip "Wikipedia" from answer

### ISSUE THREAD

**Issue by LW81** [tartanguru/alexa-google-search#10]
Hi,
Google often relies on Wikipedia information. Due to that the text blocks often have the plain word "Wikipedia" at the end. It would be nice if that would be removed .
Makes the answer a bit more natural.

**Comment by tartanguru** [comment]
Great suggestion - I will try to include in the next release

**Comment by mattrayner** [comment]
I've created pull requests for both master and version 2 branches that address this issue, let me know if you need any changes made to them :)

**Comment by tartanguru** [comment]
A similar treatment has been applied into version 2 final
