### ISSUE TITLE
Traffic cards

### ISSUE THREAD

**Issue by luigidc25** [tartanguru/alexa-google-search#12]
Hey there,
do you think it might be possible to parse traffic cards as well?
e.g. https://www.google.com/search?q=how+is+the+traffic+from+las+vegas+to+los+angeles

**Comment by tartanguru** [comment]
I will see how easy this is to implement

**Comment by luigidc25** [comment]
Cool, thanks. Of course only one (the first) possible route would be enough.

**Comment by tartanguru** [comment]
I've just investigated this and it's not going to be possible. The skill pretends to be a browser but it can't support javascript. Because of this google doesn't present a traffic card so I have nothing to parse. Sorry

**Comment by luigidc25** [comment]
Ok, thanks for investigating. I already wondered why I did not found the same elements in skill HTML response like I did in browser results. Javascript seems to be the sticking point.
