### ISSUE TITLE
exchange textual numbers to real numbers (for german google)

### ISSUE THREAD

**Issue by shivan** [tartanguru/alexa-google-search#15]
Currently textual numbers are sent to google as text.

In this case "siebzig dollar in euro" does not work. But only in german. English works well with textual numbers.

Solution could be something like this:
http://stackoverflow.com/questions/11980087/javascript-words-to-numbers
But converted to german.

**Comment by tartanguru** [comment]
I've looked at doing this but it is considerable work for a non German speaker like myself. Perhaps the German development community could address this?

**Comment by tartanguru** [comment]
I'm closing this issue as I am no longer supporting this project as I have released a version based upon the official API.
