### ISSUE TITLE
Cannot get past "Unknown slot type" error

### ISSUE THREAD

**Issue by jtomalley** [tartanguru/alexa-google-search#18]
After following to the letter, I STILL get this error after configuring the Interaction model on the developer console. (see pic)
What am I missing??
 
![croppercapture 1](https://cloud.githubusercontent.com/assets/26492428/24061719/cdb8161e-0b15-11e7-906b-c8a3bbaaf31a.png)

**Comment by kostasns** [comment]
Make sure 'name' in 'SearchIntent' slot is in lowercase, as well as click 'Add' after entering Custom Slot before hitting Next

**Comment by jtomalley** [comment]
I FOUND IT
There was an extra space at the end of "SEARCH"
