### ISSUE TITLE
node.js 4.3 changed on Alexa devel site. Will 6.10 work??? 

### ISSUE THREAD

**Issue by johnjces** [tartanguru/alexa-google-search#20]
Today, April 1, 2017, I was installing this Alexa Ask Google for my son and Amazon made some changes to users of node.js 4.3. You cannot change the timeout to greater than 1 second and according to the web site’s change notice, it is hard coded at 50ms.

If you choose node.js 6.10, you can change the timeout but at the moment of this writing, I do not know if the ask google skill will work with node.js 6.10. Should be downward compatible, but...

I selected node.js 6.10 but I won't know if it works till later tonight.

Does anyone have any thoughts? I’ll report when I know which will be some time from now.

PS. Not an April Fools Day Joke.

**Comment by tartanguru** [comment]
Thanks for bringing this to my attention.
I've just tested 6.10 and it works fine.

Node 4.3 doesn't work any more as it times out before the skill can finish processing - I'll update the instructions

**Comment by tartanguru** [comment]
I've moved the installation instruction to refer to selecting 6.10 and have asked the other instruction sites to move anyway as the next version of the skill has some dependencies on 6.10

**Comment by johnjces** [comment]
Thanks! I forgot to write back after testing and it works just fine on 6.10. My Alexa on v 4.3 still works fine without timing out. I guess everyone moving forward on 4.3 will have that restriction. Looking forward to the update and will move to 6.10 then!

Any hints on improvements in the next version/release?

Thanks for the work! Makes Alexa a heck of a lot smarter!
