### ISSUE TITLE
"what is the capital of new york" is not working

### ISSUE THREAD

**Issue by schwark** [tartanguru/alexa-google-search#22]
The response is in div.kno-fb-ctx. Can you also add a lookup for that div for the answer? I could fork and add, but looks like you are in the process of creating a version 2 so I figured it would be easier to file an issue instead.

**Comment by tartanguru** [comment]
I've just tried that question and I get a valid response:-

New York, Capital , Albany,

**Comment by tszumowski** [comment]
Agree. I tried as well and got a valid response today.
