### ISSUE TITLE
What about refresh Token?

### ISSUE THREAD

**Issue by warhost** [tartanguru/alexa-google-search#28]
Hey,

I am very impressed by this Skill, nice idea. I have a question concerning the authorisation and how you have managed to keep it alive without the use of refresh Tokens. Why does an account stay authorized with just the access Token here? I am also working on implementing Google Authentication into a skill, and can not figure out how to keep it authorized.

Cheers

**Comment by tartanguru** [comment]
This skill does not authenticate against anything. It just loads a google search page and parses the resulting HTML. Have a look at my other project Alexa-Assistant which does authenticate against a number of Google API's
