### ISSUE TITLE
Will this work in India

### ISSUE THREAD

**Issue by zodvk** [tartanguru/alexa-google-search#29]
Hello, 
Was excited to get this skill working using the instruction. I was able to enable the skill in the echo app but Alexa could not recognize the commands at all.
Can I get it to work in India?

Thanks

**Comment by tartanguru** [comment]
Hi this skill currently wouldn't work in India as there is no localisation for that Locale in the code. 
I've just updated the skill to support India and Canada. Additonally it will default to English(US) if the locale is not found
