### ISSUE TITLE
Not working on device (accounts are all correct)

### ISSUE THREAD

**Issue by phairplay** [tartanguru/alexa-google-search#3]
Hi,
I've gone through all the steps and when I test it I see the correct result, yet it doesn't work on the device.

I've checked to ensure all accounts are the same as the one linked to my echo and all it correct. I've also tested the upload and got the correct result as per your fault finding. (Section 3)

Please help me :)

**Comment by mobalized** [comment]
Just to verify. If you go to the alexa app, skills, your skills does the google skill show? If you go into developer.amazon.com and go to test and type something like "apple" into the sample utterance you get the expected response from lambda with the definition of apple?

**Comment by phairplay** [comment]
Hi yes i see it I my skills

Here is the test response

{
  "version": "1.11",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak>Apple is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. <break time=\"250ms\"/> Wikipedia</speak>"
    },
    "card": {
      "content": "Apple is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. Wikipedia",
      "title": "Google Search Result for: Apple",
      "type": "Simple"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}

**Comment by tartanguru** [comment]
If you are getting a correct response in the developer test then the skill is working properly.
Are you based in the UK or US and have you got the language of the skill set correctly to the same as your device?

**Comment by phairplay** [comment]
Sir I salute you and give myself a high five to the face
My skill was set to US language not UK

**Comment by tartanguru** [comment]
Thought that might be the problem!

Closing issue
