### ISSUE TITLE
German support not working (Version 1.5)

### ISSUE THREAD

**Issue by GooglyEyz** [tartanguru/alexa-google-search#5]
German support isn't working in version 1.5.1, because after locales are set by if-statement in line #450 to DE, they are overwritten with default value US by the else statement at line #464.

**Comment by tartanguru** [comment]
Well spotted! Thanks for pointing that out. I have addressed the issue and pushed and updated version. Would you be able to retest please - sorry

**Comment by GooglyEyz** [comment]
I've tested it and the new version of index.js fixed the issue. Btw. don't forget to update archive.zip, because it still contains the old version of index.js. Thanks.

**Comment by mondface** [comment]
I've tested it with the new version of index.js. the issue is fixed for german.
thx!

**Comment by tartanguru** [comment]
Thanks guys - I have fully updated the deployment package including the zip
