### ISSUE TITLE
Fehlermeldung beim Extrahieren des ZIP-Folders

### ISSUE THREAD

**Issue by lukuku** [tartanguru/alexa-google-search#8]
Hi,

ich wollte deinen toll beschriebenen Skill gern einmal ausprobieren und stoße auf einen Fehler beim Extrahieren. Habe mal einen Screenshot beigefügt. Dies passiert bei mehreren Dateien in Folge.

Gruß

Lukuku
![fehlersuche](https://cloud.githubusercontent.com/assets/25353713/22307698/5b777b74-e344-11e6-8974-b330add037b6.png)

**Comment by PJF16** [comment]
Hey,

please write in English so that everyone understands your problem. This problem is easy. Your path is too long. Just try to extract the .zip file in for example C:\temp.

**Comment by tartanguru** [comment]
Thanks PJF16.
Closing this issue as it isn't to do with the code
