### ISSUE TITLE
Unzipping error on is-property.js

### ISSUE THREAD

**Issue by EdTheC** [tartanguru/alexa-google-search#9]
When I unzip:
Cannot create "C:\Users\xxxxx\AppData\Local\Temp\wz3e2b\alexa-google-search-master\src\node_modules\request-promise\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\is-property.js".

Not sure how big an issue this is.

**Comment by tartanguru** [comment]
This is because your windows path is too long. Unzip it in the root of the c: drive
